name:  my first workflow
on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "This is my first workflow"
      - name: check java and gradle version
        run: |
          java -version
          gradle -v

  build-project:
    runs-on: ubuntu-latest
    needs:
      - run-shell-commands
    steps:
      - name: build gradle project
        run: gradle build
