name:  my first workflow
on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "This is my first workflow"
      - name: check java and gradle version
        run: |
          java -version
          gradle -v
